-- INSERT INTO order_items (order_id, quantity, menu_item_id) VALUES (
--   1,
--   1,
--   1
-- );
-- INSERT INTO order_items (order_id, quantity, menu_item_id) VALUES (
--   1,
--   2,
--   2
-- );
-- INSERT INTO order_items (order_id, quantity, menu_item_id) VALUES (
--   1,
--   1,
--   3
-- );
-- INSERT INTO order_items (order_id, quantity, menu_item_id) VALUES (
--   2,
--   1,
--   4
-- );
-- INSERT INTO order_items (order_id, quantity, menu_item_id) VALUES (
--   2,
--   2,
--   5
-- );
-- INSERT INTO order_items (order_id, quantity, menu_item_id) VALUES (
--   2,
--   3,
--   6
-- );
